version: '3'

services:

  postgres:
    container_name: postgres
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
      container_name: orderly
      build: .
      restart: always
      entrypoint: /entrypoint.sh
      stdin_open: true
      tty: true
      ports:
        - "8000:8000"
      volumes:
        - ./broken_django:/home/broken_django
      links:
        - postgres
      depends_on:
        - postgres

volumes:
  pg_data:
